/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BasicSettings.java
 *
 * Created on Apr 6, 2013, 4:50:12 PM
 */

package Speech.settings;


import Speech.sqlconnection.MysqlConnect;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lok Bahadur Chetri<lok.b.chetri@gmail.com>
 */


public class LanguageEntry extends javax.swing.JPanel {

    /** Creates new form BasicSettings */
    Connection conn;
    private ResultSet rs = null;
    private PreparedStatement pst = null;
    
    public LanguageEntry() {
        try {
            initComponents();
            
            conn = (Connection) new MysqlConnect().getDBConnection();
        } catch (Exception ex) {
            Logger.getLogger(LanguageEntry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    //write properties to file
    
    //read properties from file and display in text fields
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     **/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        cmdSave = new javax.swing.JButton();
        txtLanguage = new javax.swing.JTextField();

        setFocusCycleRoot(true);
        setFocusable(false);

        jLabel4.setText("Enter Language");

        cmdSave.setText("Save");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLanguage)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdSave))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdSave)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        // TODO add your handling code here:
        
        String language=txtLanguage.getText().trim();
        if(language.length()==0 || language==null)
            JOptionPane.showMessageDialog(null, "Please enter language first","Warning",JOptionPane.WARNING_MESSAGE);
        else
        {
            //add to database
            
            String q = "insert into sid_language_master (language)values('"+language+"')";
            try {
                pst = conn.prepareStatement(q);
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(LanguageEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
            

            JOptionPane.showMessageDialog(null, "New language saved successfully !", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSave;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtLanguage;
    // End of variables declaration//GEN-END:variables

}
