/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on Jan 15, 2013, 12:39:43 PM
 */
package Speech.authentication;

//import Speech.common.GetMessage;
import Speech.gui.MainFrame;
import Speech.settings.DBConf;
import Speech.settings.ServerConfiguration;
import Speech.sqlconnection.MysqlConnect;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tatapower SED
 *
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private Connection conn = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;
    public String userName;

    public login() throws Exception {
        initComponents();
        centerScreen();

    }

    private void centerScreen() {
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Speech/Icons/title.png")).getImage());
        Dimension dim = this.getToolkit().getScreenSize();
        int screenWidth = dim.width;
        int screenHeight = dim.height;
        int frameWidth = screenWidth / 3;
        int frameHeight = screenHeight / 3;
        //this.setSize(frameWidth,frameHeight);
        this.setLocation((screenWidth - frameWidth) / 2, (screenHeight - frameHeight) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextUsername = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jTextPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        serverConf = new javax.swing.JMenuItem();
        connectionInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NasoSpeech");
        setMinimumSize(new java.awt.Dimension(450, 300));
        setPreferredSize(new java.awt.Dimension(420, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelLogin.setLayout(null);

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME");
        jPanelLogin.add(jLabel2);
        jLabel2.setBounds(80, 80, 93, 15);

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        jPanelLogin.add(jLabel3);
        jLabel3.setBounds(80, 130, 100, 20);

        jTextUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextUsernameKeyPressed(evt);
            }
        });
        jPanelLogin.add(jTextUsername);
        jTextUsername.setBounds(180, 80, 178, 20);

        jButtonLogin.setBackground(new java.awt.Color(102, 204, 255));
        jButtonLogin.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("LOGIN");
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseClicked(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonLogin);
        jButtonLogin.setBounds(180, 180, 90, 25);

        jTextPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPasswordMouseClicked(evt);
            }
        });
        jTextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPasswordActionPerformed(evt);
            }
        });
        jTextPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPasswordKeyPressed(evt);
            }
        });
        jPanelLogin.add(jTextPassword);
        jTextPassword.setBounds(180, 130, 178, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Speech/Icons/btn_speech_backgound4.jpeg"))); // NOI18N
        jLabel1.setText(" ");
        jPanelLogin.add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 290);

        jMenuBar1.setBackground(new java.awt.Color(102, 204, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(102, 204, 255));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Settings");

        serverConf.setBackground(new java.awt.Color(102, 204, 255));
        serverConf.setForeground(new java.awt.Color(255, 255, 255));
        serverConf.setText("Server Configuration");
        serverConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverConfActionPerformed(evt);
            }
        });
        jMenu1.add(serverConf);

        connectionInfo.setBackground(new java.awt.Color(102, 204, 255));
        connectionInfo.setForeground(new java.awt.Color(255, 255, 255));
        connectionInfo.setText("Connection info");
        connectionInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionInfoActionPerformed(evt);
            }
        });
        jMenu1.add(connectionInfo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userAuthentication() {
        conn = MysqlConnect.getDBConnection();
        if (conn == null) {
            return;
        }


        String username = (jTextUsername.getText().trim()).toLowerCase();
        String password = (jTextPassword.getText().trim());

        if (username.length() < 1 || password.length() < 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "username and/or password should not empty");
            return;
        }


        try {
            String querty = "select * from authentication where LOWER(user_id)=? and password=?";
            pst = conn.prepareStatement(querty);
            pst.setString(1, username);
            pst.setString(2, password);
            rs = pst.executeQuery();
            if (rs.next()) {
                //JOptionPane.showMessageDialog(null,"username and password is correct !");
                //--        
                String q = "update authentication set status=1 where LOWER(user_id)='" + username + "'";
                pst = conn.prepareStatement(q);
                pst.execute();
                //--
                String roll = rs.getString("roll");
                this.dispose();
                //set username
                MainFrame mf = new MainFrame(username, roll);
                mf.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Invalid username or password. Try again!", "Warning", JOptionPane.WARNING_MESSAGE);
                jTextUsername.requestFocus();
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:      
    }//GEN-LAST:event_formWindowOpened

    private void serverConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverConfActionPerformed
        // TODO add your handling code here:

        JDialog dialog = new JDialog();
        dialog.add(new ServerConfiguration());
        dialog.setAlwaysOnTop(false);
        dialog.setModal(true);
        dialog.setResizable(false);
        dialog.setTitle("Server Configuration");
        dialog.setLayout(new BorderLayout());
        JPanel pane = (JPanel) dialog.getContentPane();
        pane.setPreferredSize(new Dimension(275, 150));
        Dimension screen = this.getToolkit().getScreenSize();
        dialog.setLocation((int) (screen.width - 275) / 2, (int) (screen.height - 150) / 2);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_serverConfActionPerformed

    private void connectionInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionInfoActionPerformed
        // TODO add your handling code here:
        JDialog dialog = new JDialog();
        dialog.add(new DBConf());
        dialog.setAlwaysOnTop(false);
        dialog.setModal(true);
        dialog.setResizable(false);
        dialog.setTitle("Mysql Connection");
        dialog.setLayout(new BorderLayout());
        JPanel pane = (JPanel) dialog.getContentPane();
        pane.setPreferredSize(new Dimension(300, 230));
        Dimension screen = this.getToolkit().getScreenSize();
        dialog.setLocation((int) (screen.width - 275) / 2, (int) (screen.height - 150) / 2);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_connectionInfoActionPerformed

    private void jTextPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonLogin.requestFocus();
        }
    }//GEN-LAST:event_jTextPasswordKeyPressed

    private void jTextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPasswordActionPerformed
        // TODO add your handling code here:
        userAuthentication();
    }//GEN-LAST:event_jTextPasswordActionPerformed

    private void jTextPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasswordMouseClicked

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:

        userAuthentication();
        this.dispose();
        // MainFrame mf = new MainFrame("tata", "1");
        //mf.setVisible(true);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoginMouseClicked

    private void jTextUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUsernameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextPassword.requestFocus();
        }
    }//GEN-LAST:event_jTextUsernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
/*UIManager.put("Synthetica.window.decoration", Boolean.FALSE);
        try {
            UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
        }*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new login().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem connectionInfo;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jTextPassword;
    private javax.swing.JTextField jTextUsername;
    private javax.swing.JMenuItem serverConf;
    // End of variables declaration//GEN-END:variables
}
