/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Speech.user;

import Speech.gui.MainFrame;
import Speech.sqlconnection.MysqlConnect;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tatapower SED
 *
 */
public class CreateNewUsers extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewUsers
     */
    private Connection conn;

    public CreateNewUsers(MainFrame mainframe) {
        initComponents();
        conn = (Connection) MysqlConnect.getDBConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPWS = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtrePWS = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        comRole = new javax.swing.JComboBox();

        jLabel1.setText("User ID");

        jLabel2.setText("Password");

        jLabel3.setText("re-type Password");

        jLabel4.setText("Role");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        comRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtrePWS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPWS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comRole, javax.swing.GroupLayout.Alignment.LEADING, 0, 180, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPWS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtrePWS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(comRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clearAllText();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void clearAllText() {
        txtUserID.setText("");
        txtPWS.setText("");
        txtrePWS.setText("");
        comRole.setSelectedIndex(0);


    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String userID = txtUserID.getText().trim();
        String pws = txtPWS.getText().toString().trim();
        String repws = txtrePWS.getText().toString().trim();
        String role = comRole.getSelectedItem().toString().trim();


        if (userID.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter UserID");
            return;
        }

        if (pws.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter password");
            return;
        }

        if (!(pws.equals(repws))) {
            javax.swing.JOptionPane.showMessageDialog(this, "Re-type password is not correct");
            return;
        }

        if (role.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter Role");
            return;
        }
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            // Statements allow to issue SQL queries to the database
            statement = conn.createStatement();
            // Result set get the result of the SQL query
            resultSet = statement.executeQuery("select * from authentication where LOWER(user_id) = '" + userID.toLowerCase() + "'");

            if (resultSet.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "User already available !", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }


        } catch (SQLException er) {
            Logger.getLogger(CreateNewUsers.class.getName()).log(Level.SEVERE, null, er);
        } finally {
            try {
                if (statement != null) {
                    statement.close();
                }
                if (resultSet != null) {
                    resultSet.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(CreateNewUsers.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        String q = "insert into authentication (user_id,password,roll,status)values('" + userID + "','" + pws + "','" + role + "',0)";
        PreparedStatement pst = null;
        try {
            pst = conn.prepareStatement(q);
            int success = pst.executeUpdate();
            if (success > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "New user created successfully !", "Information", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "New user creation fail !", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(CreateNewUsers.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (pst != null) {
                try {
                    pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(CreateNewUsers.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


        clearAllText();



    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPWS;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JPasswordField txtrePWS;
    // End of variables declaration//GEN-END:variables
}
